language: go
go:
- 1.12.9
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Renée Singer"
  - GIT_EMAIL="e1028092@student.tuwien.ac.at"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="blog"
before_install:
- openssl aes-256-cbc -K $encrypted_d6b07742d8a8_key -iv $encrypted_d6b07742d8a8_iv
  -in travis_key.enc -out travis_key -d
install:
- go get -v github.com/gohugoio/hugo
script:
- hugo
- "./scripts/deploy.sh"
after_success: 
