language: go
go:
- 1.6.2
env:
  global:
  - SSH_KEY="travis_key"
  - GIT_NAME="Kevin Singer"
  - GIT_EMAIL="e1028092@student.tuwien.ac.at"
  - SOURCE_DIR="public"
  - DEPLOY_BRANCH="blog"
before_install:
- openssl aes-256-cbc -K $encrypted_2531e4b3a730_key -iv $encrypted_2531e4b3a730_iv
  -in travis_key.enc -out travis_key -d
- go version
- sudo apt-get -qq update
- sudo apt-get install -y golang
- go version
install:
- go get -v github.com/spf13/hugo
script:
- hugo
- "./scripts/deploy.sh"
after_success: 
