# config.toml
# theme and config based on https://github.com/CrimsonRay/slender

baseurl = "https://pheara.github.io/"
title = "Pheara’s Ramblings"
languageCode = "en-US"
MetaDataFormat = "toml"
theme = "hugo-theme-pixyll-modified"
Paginate = 5
PaginatePath = "/"

[author]
    name = "Pheara"

[permalinks]
    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    # tagline = "120% guaranteedly inconsistent"

    # Footer; Markdown accepted here.
    footer = ""

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "A collection of ideas, designs and essays created over the course Pheara's Media and Human Centered Computing Studies"
    keywords = "game design, sociology of technology, human computer interaction, pheara"

    # Google Analytics
    # Remove, comment, or leave it blank if you don't have one.
    ganalytics = ""

[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = ""
    weight     = 0

    [[menu.main]]
    identifier = "about"
    name       = "about"
    url        = "about/"
    weight     = 1

    [[menu.main]]
    identifier = "contact"
    name       = "contact"
    url        = "contact/"
    weight     = 2

[taxonomies]
tag = "tags"
